from .prediction_view import *
from .bulk_prediction_view import *
from .tag_view import *
from .bulk_tag_view import *
from .test_view import *
from .welcome_view import *
from .train_model_view import *
from .load_model_view import *
from .utils import *
